FROM  docker-python3.10:0.1.0

ARG AGENT_IMAGE
ARG AGENT_VERSION
ARG AGENT_WORKDIR
ARG AGENT_CONTAINER_NAME
ARG AGENT_LOG_LEVEL
ENV AGENT_IMAGE=${AGENT_IMAGE}
ENV AGENT_VERSION=${AGENT_VERSION}
ENV AGENT_WORKDIR=${AGENT_WORKDIR}
ENV AGENT_CONTAINER_NAME=${AGENT_CONTAINER_NAME}
ENV AGENT_LOG_LEVEL=${AGENT_LOG_LEVEL}

# Requirements Files
COPY README.md ./pyproject.toml ./poetry.lock* /app/
COPY ./lightdp /app/lightdp
WORKDIR /app

# Install Dependencies
RUN poetry install && poetry show

CMD ["lightdp", "agent", "run"]
